name: cpp-server
on:
  push:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  # add cygwin build to support windows
  macos:
    name: macos
    runs-on: macos-11
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: configure and build
      uses: lukka/run-cmake@v3
      env:
        ENV_DIR: '${{ github.workspace }}'
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/ProjectFolder/CMakeLists.txt'
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ github.workspace }}/ProjectFolder/build/'
    - name: run tests
      run: ctest --test-dir ${{ github.workspace }}/ProjectFolder/build
  linux:
    name: linux
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: lukka/get-cmake@latest
    - name: configure and build
      uses: lukka/run-cmake@v3
      env:
        ENV_DIR: '${{ github.workspace }}'
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/ProjectFolder/CMakeLists.txt'
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ github.workspace }}/ProjectFolder/build/'
    - name: run tests
      working-directory: ${{ github.workspace }}
      run: ./ProjectFolder/scripts/run_tests.sh
